# generated by: rails g generator service
class ServiceGenerator < Rails::Generators::NamedBase
  source_root File.expand_path('templates', __dir__)

  # credit: https://arsfutura.com/magazine/diy-create-your-own-rails-generator/
  class_option :mkdir, type: :boolean

  def create_service_file
    # puts "n: #{name}"
    # puts "cn: #{class_name}"
    # puts "fn: #{file_name}"
    module_path = name.split("::")[..-2]
    file_dir = File.join("app/services", module_path)
		if !File.exist?(file_dir) && !options[:mkdir]
      puts "ERR: dir does not exist '#{File.join(module_path)}': use --mkdir"
    else
      template "service_template.erb", File.join("app/services", module_path, "#{file_name}.rb")
      template "service_spec_template.erb", File.join("spec/services", module_path, "#{file_name}_spec.rb")
    end
  end

end
